# CGR QIIME2 pipeline for microbiome analysis.
#
# AUTHORS:
#     S. Sevilla Chill
#     W. Zhou
#     B. Ballew

## Manifest
metadata_manifest: '/DCEG/Projects/Microbiome/Analysis/Project_NP0084_MB/otuclustering/manifest.txt'

## Directories
out_dir: '/DCEG/Projects/Microbiome/Analysis/Project_NP0084_MB/'
exec_dir: '/DCEG/CGF/Bioinformatics/Production/Sam/dev/QIIME_pipeline'
fastq_abs_path: '/DCEG/CGF/Sequencing/Illumina/MiSeq/PostRun_Analysis/Data'  # internal runs only
temp_dir: '/DCEG/CGF/Bioinformatics/Production/Sam/scratch'

table_dir:  '/DCEG/Projects/Microbiome/Analysis/Project_NP0084_MB/20200410_2019.1/denoising/feature_tables/merged.qza'
repseq_dir: '/DCEG/Projects/Microbiome/Analysis/Project_NP0084_MB/20200410_2019.1/denoising/sequence_tables/merged.qza'

clust_dir: '/DCEG/Projects/Microbiome/Analysis/Project_NP0084_MB/otuclustering/proj_data/'
raw_ref_dir: '/DCEG/Projects/Microbiome/Analysis/Project_NP0084_MB/otuclustering/train_classifier'
filt_file_dir: '/DCEG/Projects/Microbiome/Analysis/Project_NP0084_MB/otuclustering/proj_data/input/filt_list.tsv'

tax_dir: '/DCEG/Projects/Microbiome/Analysis/Project_NP0084_MB/taxclass/proj_data/'

## Run type
data_source: 'internal'  # 'external' or 'internal' (to CGR)
  # for external data, require an additional metadata columns called "fq1" and "fq2" with full path and file names for R1 and R2 fastqs (do they need to be zipped?)

## QIIME version
qiime2_version: '2019.1'  # 2017.11 or 2019.1

## Analysis parameters
denoise_method: 'dada2' # not yet implemented
dada2_denoise:
  trim_left_forward: 0
  trim_left_reverse: 0
  truncate_length_forward: 0
  truncate_length_reverse: 0
phred_score: 33
demux_param: 'paired_end_demux'
input_type: 'SampleData[PairedEndSequencesWithQuality]'
filt_param: 1
sampling_depth: 10000
max_depth: 54000
classify_method: 'classify-sklearn'
reference_db:  # change based on qiime version
- '/DCEG/CGF/Bioinformatics/Production/Bari/refDatabases/scikit_0.20.2_q2_2019.1/gg-13-8-99-nb-classifier.qza'
- '/DCEG/CGF/Bioinformatics/Production/Bari/refDatabases/scikit_0.20.2_q2_2019.1/silva-132-99-nb-classifier.qza'
de_novo_id: 0.99
closed_id: 0.99
open_id: 0.99

## Cluster submission parameters
cluster_mode: 'qsub -q long.q -V -j y -S /bin/bash -o /DCEG/Projects/Microbiome/Analysis/Project_NP0084_MB/otuclustering/proj_data/logs -pe by_node {threads}'  # options are 'qsub/sbatch/etc ...', 'local', 'dryrun', 'unlock'
#cluster_mode: 'unlock'
  # SGE example:    qsub -q myqueue.q -V -j y -S /bin/bash -o /path/to/project/directory/logs/ -pe by_node {threads}
  # slurm example:  sbatch --mem=64g --time=24:00:00 --output=/path/to/project/directory/logs/slurm-%j.out --cpus-per-task={threads}
num_jobs: 10
latency: 60
